AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Kafka Publisher that generates data as per the schedule
Globals:
  Function:
    Timeout: 30
Parameters:
  BucketNamePrefix:
    Type: String
    Default: gmntssplunkdeploy
Resources:
  csmstateP:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: csmstateP/
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 1024
      Timeout: 900
      Events:
        CheckWebsiteScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)